apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: votingapp
spec:
  storageClassName: votingapp-sc  
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi  
