apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: votingapp
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    name: http
    protocol: TCP
    port: 443
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
  
